-- AddColumns (converted from SQLite RedefineTables)
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "exitIntentEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "timeDelayEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "timeDelaySeconds" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "cartValueEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "cartValueMin" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "cartValueMax" REAL NOT NULL DEFAULT 1000;
