-- AddColumns (converted from SQLite RedefineTables)
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "mutationRate" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "crossoverRate" INTEGER NOT NULL DEFAULT 70;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "selectionPressure" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "populationSize" INTEGER NOT NULL DEFAULT 10;
