-- AlterTable
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "brandAccentColor" TEXT DEFAULT '#f59e0b';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "brandFont" TEXT DEFAULT 'system';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "brandLogoUrl" TEXT;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "brandPrimaryColor" TEXT DEFAULT '#000000';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "brandSecondaryColor" TEXT DEFAULT '#ffffff';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "customCSS" TEXT;
