-- AddColumns (converted from SQLite RedefineTables)
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "customerCount" INTEGER;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "orderCount" INTEGER;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "avgRating" REAL;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "socialProofEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "socialProofType" TEXT NOT NULL DEFAULT 'orders';
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "socialProofMinimum" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Shop" ADD COLUMN IF NOT EXISTS "socialProofUpdatedAt" TIMESTAMP;
